# Generated by Django 3.0.5 on 2020-04-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, db_column='seriesYear', null=True)),
                ('transmission', models.SmallIntegerField(choices=[('M', 'Mechanical'), ('A', 'Automatic'), ('R', 'Robotic')], db_column='standardTransmission', max_length=8)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
