# Generated by Django 3.0.5 on 2020-04-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.SmallIntegerField(choices=[('M', 'Mechanical'), ('A', 'Automatic'), ('R', 'Robotic')], db_column='standardTransmission'),
        ),
    ]
