# Generated by Django 3.0.5 on 2020-04-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200417_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.SmallIntegerField(choices=[(1, 'Mechanical'), (2, 'Automatic'), (3, 'Robotic')], db_column='standardTransmission'),
        ),
    ]
